### PR TITLE
Fix typo in Dockerfile

### PR DESCRIPTION
**Pull request by kunitoo**
Although it operates even before modification, I fix it because I think it is typo.

### CODE REVIEW

**Comment by mtsmfm** [comment]
@kunitoo Good catch!

Could you re-commit via `git commit --amend --reuse-message HEAD` and force push?
I missed CI setting to build forked pull requests 😅

**Comment by kunitoo** [comment]
> Could you re-commit via git commit --amend --reuse-message HEAD and force push?

@mtsmfm I tried that command. Is this okay?

**Comment by mtsmfm** [comment]
@kunitoo Thanks!
The newer version will be available within 30 min!

https://hub.docker.com/r/mtsmfm/yaichi/tags/

**Comment by kunitoo** [comment]
Thank you for merging and release.

**Pull request merged**
